on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name : Setup Node ^14
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: if [ -f "tests/*" ]; then npm run test; fi
      - name: Lint with eslint
        run: npm run eslint
      - name: Check with prettier
        run: npm run prettier
